cbmex('open',0,'central-addr','192.168.137.1','instance',1);
pause(1);
cbmex('fileconfig','','',0,'instance',1);
fprintf('Attempting NSP 1 recording to file: %s\n', fileout);
pause(1);
fcomment = sprintf('File recording started at %s\n', datestr(now));
cbmex('fileconfig',fileout,fcomment,1,'instance',1);
pause(2);
fprintf(fcomment);
is_recording = true;