cbmex('open');
pause(1);
cbmex('fileconfig','','',0);
fprintf('Attempting NSP 1 recording to file: %s\n', fileout);
pause(1);
fcomment = sprintf('File recording started at %s\n', datestr(now));
cbmex('fileconfig',fileout,fcomment,1);
pause(2);
fprintf(fcomment);
is_recording = true;